---
- name: Update repository nginx
  apt_repository: repo='ppa:nginx/stable' state=present update_cache=yes
  sudo: true

- name: install nginx
  apt:
   name="nginx"
   state=present
   update_cache=true

- name: Config service nginx
  template: src=default dest=/etc/nginx/sites-enabled/default

- name: Copy index.html
  template: src=index.html dest=/var/www/html/index.html
